;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; │░Modified░By░Birkhoff░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[colors]
bg = ${xrdb:color0:#222}
fg = ${xrdb:color7:#222}
c1 = ${xrdb:color1:#222}
c2 = ${xrdb:color2:#222}
c6 = ${xrdb:color6:#222}

[bar/bar]
monitor = ${env:MONITOR:LVDS-1}
width = 100%
height = 30
bottom = false

font-0 = Iosevka Nerd Font:size=8;2
font-1 = Iosevka Nerd Font:size=8;2
font-2 = Iosevka Nerd Font:size=8;2

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 1
line-color = ${colors.c2}

; border-left-size = 2
; border-right-size = 2
; border-top-size = 2
; border-bottom-size = 2
; border-color = #00000000

padding-left = 2
padding-right = 2

module-margin-left = 2
module-margin-right = 2

modules-left = menu i3 xwindow
modules-center = mpd
modules-right = volume wlan eth cpu memory filesystem date battery sysmenu

[module/menu]
type = custom/text

content = 
content-font = 2
content-background = ${colors.bg}
content-foreground = ${colors.c2}
content-padding = 0

click-left = ~/.config/polybar/fin/scripts/launcher.sh &
;;click-middle = path_to_script
;;click-right = path_to_script

;;scroll-up = path_to_script
;;scroll-down = path_to_script
	
[module/i3]
type = internal/i3
format = <label-state>
index-sort = true

label-mode-padding = 2
label-mode-foreground = ${colors.fg}
label-mode-background = ${colors.bg}

; focused = Active workspace on focused monitor
label-focused = %name%
label-focused-background = ${colors.bg}
label-focused-foreground = ${colors.c2}
label-focused-underline = ${colors.c2}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %name%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = 2

; urgent = Workspace with urgency hint set
label-urgent = %name%
label-urgent-background = ${self.label-focused-background}
label-urgent-foreground = ${colors.c6}
label-urgent-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:35:...%

format-prefix = " "
format-prefix-foreground = ${colors.c2}
format-underline = ${colors.c2}

label-indicator-padding = 2
label-indicator-margin = 2
label-indicator-background = ${colors.c2}
label-indicator-underline = ${colors.c2}

[module/mpd]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
;;host = 127.0.0.1
;;port = 6600
;;password = mysecretpassword

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 2

; Available tags:
;   <label-song> (default)
;   <label-time>
;   <bar-progress>
;   <toggle> - gets replaced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-random>
;   <icon-repeat>
;   <icon-repeatone> (deprecated)
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
;   <icon-consume>
;   <icon-prev>
;   <icon-stop>
;   <icon-play>
;   <icon-pause>
;   <icon-next>
;   <icon-seekb>
;   <icon-seekf>

format-online =  <label-song> <icon-prev> <toggle> <icon-stop> <icon-next>
;;format-online-prefix = " "
;;format-online-prefix-font = 2
;;format-online-prefix-foreground = ${color.GREEN}

format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = <icon-prev> <toggle> <icon-next>

; Available tags:
;   <label-offline>
;format-offline = <label-offline>

; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; Default: %artist% - %title%
label-song =  %title%
label-song-maxlen = 25
label-song-ellipsis = true

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
;;abel-time = %elapsed% / %total%

; Available tokens:
;   None
label-offline = Offline

; Only applies if <icon-X> is used
icon-play = 
icon-play-font = 2
icon-pause = 
icon-pause-font = 2
icon-stop = 
icon-prev = 玲
icon-prev-font = 2
icon-next = 怜
icon-next-font = 2

; Used to display the state of random/repeat/repeatone/single
; Only applies if <icon-[random|repeat|repeatone|single]> is used
;;toggle-on-foreground = #ff
;;toggle-off-foreground = #55

[module/volume]
type = internal/alsa

format-volume = <label-volume> <bar-volume>
label-volume = 
label-volume-foreground = ${colors.fg}

format-muted-prefix = " "
format-muted-foreground = ${colors.c6}
label-muted = muted

bar-volume-width = 10
bar-volume-foreground-0 = ${colors.fg}
bar-volume-foreground-1 = ${colors.fg}
bar-volume-foreground-2 = ${colors.fg}
bar-volume-foreground-3 = ${colors.fg}
bar-volume-foreground-4 = ${colors.fg}
bar-volume-foreground-5 = ${colors.c6}
bar-volume-gradient = false
bar-volume-indicator = 
bar-volume-indicator-font = 2
bar-volume-fill = ▶
bar-volume-fill-font = 2
bar-volume-empty = ▷ 
bar-volume-empty-font = 2
bar-volume-empty-foreground = ${colors.fg}

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.c2}
format-underline = ${colors.c2}
label = %percentage%%

[module/memory]
type = internal/memory
interval = 2
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.c2}
format-underline = ${colors.c2}
label = %percentage_used%%

[module/filesystem]
type = internal/fs
mount-0 = /home
interval = 10
fixed-values = true

format-mounted = <label-mounted>
format-mounted-underline = ${colors.c2}

format-mounted-prefix = 
format-mounted-prefix-font = 2
format-mounted-prefix-foreground = ${colors.c2}
format-mounted-prefix-underline = ${colors.c2}

format-unmounted = <label-unmounted>
format-unmounted-underline = ${colors.c6}

format-unmounted-prefix = 
format-unmounted-prefix-font = 2
format-unmounted-prefix-foreground = ${colors.c6}
format-unmounted-prefix-underline = ${colors.c6}

label-mounted = " %free%"
label-unmounted = " %mountpoint%: NM"

[module/wlan]
type = internal/network
interface = wlo1
interval = 2.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = ${colors.c2}
label-connected = %essid%

format-disconnected =

ramp-signal-0 = ▁
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-5 = 
ramp-signal-6 = 
ramp-signal-7 = 

ramp-signal-foreground = ${colors.fg}

[module/eth]
type = internal/network
interface = enp3s0
interval = 2.0

format-connected-underline = ${colors.c2}
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.c2}
label-connected = %local_ip%

format-disconnected =

[module/date]
type = internal/date
interval = 1

date = " %Y-%m-%d"

time = %H:%M

format-prefix = " "
format-prefix-foreground = ${colors.fg}
format-underline = ${colors.c2}

label = %date% | %time%

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 100

format-charging = <animation-charging> <label-charging>
label-charging = %percentage%%
format-charging-underline = ${colors.c2}

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
format-discharging-underline = ${colors.c2}

format-full-prefix = " "
format-full-prefix-foreground = ${colors.c6}
format-full-underline = ${colors.c6}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.c2}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.c2}
animation-charging-framerate = 750

[module/sysmenu]
type = custom/text

content = 
content-font = 2
content-background = ${colors.bg}
content-foreground = ${colors.c6}
content-padding = 0

click-left = ~/.config/polybar/fin/scripts/powermenu.sh &

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 0
