;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	   ______      __               
;;	  / ____/___  / /___  __________
;;	 / /   / __ \/ / __ \/ ___/ ___/
;;	/ /___/ /_/ / / /_/ / /  (__  ) 
;;	\____/\____/_/\____/_/  /____/  
;;
;; 	Modified By Birkhoff
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; Active Colors
bg = ${xrdb:color0:#222}
fg = ${xrdb:color7:#222}
ac = ${xrdb:color2:#222}
mf = ${xrdb:color4:#222}

trans = #00000000
white = #FFFFFF
black = #000000

;; Material Colors
;red = #EC7875
;pink = #EC407A
;purple = #BA68C8
;blue = #42A5F5
;cyan = #4DD0E1
;teal = #00B19F
;green = #61C766
;lime = #B9C244
;yellow = #FDD835
;amber = #FBC02D
;orange = #E57C46
;brown = #AC8476
;indigo = #6C77BB
;gray = #9E9E9E
;blue-gray = #6D8895

red = ${xrdb:color2:#222}
pink = ${xrdb:color2:#222}
purple = ${xrdb:color2:#222}
blue = ${xrdb:color2:#222}
cyan = ${xrdb:color2:#222}
teal = ${xrdb:color2:#222}
green = ${xrdb:color2:#222}
lime = ${xrdb:color2:#222}
yellow = ${xrdb:color2:#222}
amber = ${xrdb:color2:#222}
orange = ${xrdb:color2:#222}
brown = ${xrdb:color2:#222}
gray = ${xrdb:color2:#222}
indigo = ${xrdb:color2:#222}
blue-gray = ${xrdb:color2:#222}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;	    __________  ______
;;	   / ____/ __ \/ ____/
;;	  / __/ / / / / /_    
;;	 / /___/ /_/ / __/    
;;	/_____/\____/_/       
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
