;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	   ______      __               
;;	  / ____/___  / /___  __________
;;	 / /   / __ \/ / __ \/ ___/ ___/
;;	/ /___/ /_/ / / /_/ / /  (__  ) 
;;	\____/\____/_/\____/_/  /____/  
;;
;; 	Modified By Birkhoff
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Active Colors
bg = ${xrdb:color0:#222}
fg = ${xrdb:color7:#222}
ac = ${xrdb:color2:#222}
mf = ${xrdb:color4:#222}

trans = #00000000
white = #FFFFFF
black = #000000

;; Material Colors
red = #F06A6A
pink = #EC1850
purple = #BA40A0
blue = #427DCD
cyan = #4DA8B9
teal = #008978
green = #5CAC30
lime = #B9A41C
yellow = #D2A91D
amber = #FD890F
orange = #EA7222
brown = #AC5C4E
grey = #8C8C8C
indigo = #4759C6
blue-gray = #6D8895

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;	    __________  ______
;;	   / ____/ __ \/ ____/
;;	  / __/ / / / / /_    
;;	 / /___/ /_/ / __/    
;;	/_____/\____/_/       
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
