#!/bin/bash
#
# By Birkhoff
#    

# Source term colors to use
. $HOME/.cache/wal/colors.sh

# Specify the todo file to read from
todofile="$HOME/.todo/todo.txt"
image="$HOME/"
title="TODO LIST" # notify title

# A function to read the todo file and nicely format the texts
prettyNotify() {
   summary=""         # initialize message summary
   summary_counter=0  # initialize number of todo list
   
   if [[ -s "$todofile" ]];then
           while IFS= read -r line
           do
                  (( summary_counter += 1 ))
                  # Create a message summary
                  summary="$summary\n<span foreground='$color1'>  ${summary_counter}. </span><span foreground='$color1'>$line</span>"
           done < "$todofile" 
   else
           summary="<span foreground='$color5'>ERROR: </span> <span foreground='$color5'>$todofile empty/not found</span> "
   fi
}

prettyNotify
notify-send -i $image "$title" "$summary"
