#!/bin/sh

# ----------------------------------------------
# Descritpion : ColorScheme Switcher
# Autor : Berthose Fin (Thos)
# Date : 2024-04-13
# ----------------------------------------------

# Définir une fonction pour changer les paramètres dans gtk-3.0/settings.ini
change_gtk_settings() {
    local theme_name="$1"
    local icon_theme="$2"
    local cursor_theme="$3"

    sed -i "s/^gtk-theme-name=.*/gtk-theme-name=${theme_name}/" ~/.config/gtk-3.0/settings.ini
    sed -i "s/^gtk-icon-theme-name=.*/gtk-icon-theme-name=${icon_theme}/" ~/.config/gtk-3.0/settings.ini
    sed -i "s/^gtk-cursor-theme-name=.*/gtk-cursor-theme-name=${cursor_theme}/" ~/.config/gtk-3.0/settings.ini
}

# Définir une fonction pour changer la configuration de Vim (~/.vimrc)
change_vim_settings() {
    local colorscheme="$1"

    sed -i "s/^let g:lightline = .*/let g:lightline = { 'colorscheme': '${colorscheme}' }/" ~/.vimrc
}

# Définir une fonction pour changer l'image_dir dans ~/.bin/randomwall
change_randomwall_image_dir() {
    local image_dir="$1"

    sed -i "s|^image_dir=.*|image_dir=\"${image_dir}\"|" ~/.bin/randomwall
}

# ----------------------------------------------
# Menu de sélection du ColorScheme
# ----------------------------------------------

options="\
catppuccin-frappe
catppuccin-latte
catppuccin-macchiato
catppuccin-mocha
dracula
gruvbox
nord
quit"

choice=$(printf '%s\n' "${options}" | rofi -dmenu -i -l 20 -p 'ColorScheme')

if ! [ "${choice}" ] || [ "${choice}" = "quit" ]; then
    printf 'No theme chosen\n' >&2
    exit 1
fi

# Changer les paramètres en fonction du choix
case "${choice}" in
    catppuccin-frappe)
        wal --theme "${choice}"
        change_gtk_settings "Catppuccin-Frappe-Standard-Blue-Dark" "Fluent-dark" "Catppuccin-Frappe-Dark-Cursors"
        change_vim_settings "catppuccin_frappe"
        change_randomwall_image_dir "$HOME/Images/Catppuccin"
        ;;
    catppuccin-latte)
        wal --theme "${choice}" -l
        change_gtk_settings "Catppuccin-Latte-Standard-Blue-Light" "Fluent" "Catppuccin-Latte-Dark-Cursors"
        change_vim_settings "catppuccin_latte"
        change_randomwall_image_dir "$HOME/Images/Light"
        ;;
    catppuccin-macchiato)
        wal --theme "${choice}"
        change_gtk_settings "Catppuccin-Macchiato-Standard-Blue-Dark" "Fluent-dark" "Catppuccin-Macchiato-Dark-Cursors"
        change_vim_settings "catppuccin_macchiato"
        change_randomwall_image_dir "$HOME/Images/Catppuccin"
        ;;
    catppuccin-mocha)
        wal --theme "${choice}"
        change_gtk_settings "Catppuccin-Mocha-Standard-Blue-Dark" "Fluent-dark" "Catppuccin-Mocha-Dark-Cursors"
        change_vim_settings "catppuccin_mocha"
        change_randomwall_image_dir "$HOME/Images/Catppuccin"
        ;;
    dracula)
        wal --theme "${choice}"
        change_gtk_settings "Dracula" "dracula-icons" "Dracula-cursors"
        change_vim_settings "${choice}"
        change_randomwall_image_dir "$HOME/Images/Dracula"
        ;;
    gruvbox)
        wal --theme "${choice}"
        change_gtk_settings "Gruvbox-Dark-BL-MOD" "Gruvbox-plus-icon-MOD" "Gruvbox_Cursors_Dark"
        change_vim_settings "${choice}"
        change_randomwall_image_dir "$HOME/Images/Gruvbox"
        ;;
    nord)
        wal --theme "${choice}"
        change_gtk_settings "Nordic-darker" "Nordic-Darker" "Nordic-cursors"
        change_vim_settings "${choice}"
        change_randomwall_image_dir "$HOME/Images/Nord"
        ;;
    *)
        echo "Choix de thème non pris en charge : ${choice}" >&2
        exit 1
        ;;
esac

# alacritty
sed -i "s|^import = .*|import = [\"~/.config/alacritty/colorschemes/${choice}.toml\"]|" ~/.config/alacritty/alacritty.toml

# dunst
cp ~/.config/dunst/colorschemes/${choice} ~/.config/dunst/dunstrc
pkill dunst
dunst &

# rofi
sed -i "s|^@theme .*|@theme \"~/.config/rofi/themes/${choice}.rasi\"|" ~/.config/rofi/config.rasi

# ulauncher
sed -i "s/\"theme-name\": .*/\"theme-name\": \"${choice}\"/" ~/.config/ulauncher/settings.json

# zathura
sed -i "s|^include .*$|include colorschemes/${choice}|" ~/.config/zathura/zathurarc

# Redémarrer randomwall avec le nouveau image_dir
pkill -f randomwall
sleep 1
nohup sh ~/.bin/randomwall >/dev/null 2>&1 &

# Redémarrer i3wm
i3-msg restart