#!/bin/bash

# ----------------------------------------------
# Descritpion : Polybar style changer
# Autor : Berthose Fin (Thos)
# Date : 2023-04-06
# ----------------------------------------------

DIR="$HOME/.config/polybar"
STYLE=$(sed -n '4s/STYLE=//p' "$DIR/launch.sh")

case "$1" in
	"default"|"blocks"|"docky"|"forest"|"grayblocks"|"material"|"minimal")
		style="$1"
		sed -i "s/$STYLE/$1/g" "$DIR/launch.sh"
		sh "$DIR/launch.sh"
		;;
	*)
		cat <<- EOF
		Spolybar - polybar style changer

		Usage:
		spolybar [THEME]

		Available Themes :
		- default
		- blocks
		- docky
		- forest
		- grayblocks
		- material
		- minimal
		EOF
		;;
esac