#!/bin/bash

# ----------------------------------------------
# Descritpion : Change polybar style
# Autor : Berthose Fin (birkhoff)
# Date : 2021-02-09
# ----------------------------------------------

DIR="$HOME/.config/polybar"
STYLE=$(sed -n '4s/STYLE=//p' $DIR/launch.sh);

if [[ "$1" == "blocks" ]]; then
	style="blocks"
    	sed -i "s/$STYLE/$1/g" $DIR/launch.sh
	sh $DIR/launch.sh

elif [[ "$1" == "fin" ]]; then
	style="fin"
	sed -i "s/$STYLE/$1/g" $DIR/launch.sh
	sh $DIR/launch.sh

elif [[ "$1" == "forest" ]]; then
	style="forest"
   	sed -i "s/$STYLE/$1/g" $DIR/launch.sh
	sh $DIR/launch.sh

elif [[ "$1" == "grayblocks" ]]; then
	style="grayblocks"
    	sed -i "s/$STYLE/$1/g" $DIR/launch.sh
	sh $DIR/launch.sh

elif [[ "$1" == "topy" ]]; then
	style="topy"
	sed -i "s/$STYLE/$1/g" $DIR/launch.sh
	sh $DIR/launch.sh

elif [[ "$1" == "wave" ]]; then
	style="wave"
	sed -i "s/$STYLE/$1/g" $DIR/launch.sh
	sh $DIR/launch.sh

else
	cat <<- EOF
	Usage : spolybar [THEME]
		
	Available Themes :
	- blocks	- fin	- forest
	- grayblocks	- topy	- wave
	EOF
fi
