#!/bin/bash
#
# By Birkhoff
#

rofi -modi run,drun \
	-display-drun "Applications :" -drun-display-format "{name}" \
	-show drun \
	-location 1 \
	-xoffset 5 \
	-yoffset 33 \
	-line-padding 4 \
	-columns 1 \
	-width 25 \
	-lines 20 \
	-padding 25 \
	-hide-scrollbar \
	-show-icons
