#!/bin/bash

## By Birkhoff

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 6 <<< "> Lock|> Exit|> Suspend|> Hibernate|> Reboot|> Shutdown")"
            case "$MENU" in
		*Lock) ~/.bin/blurlock ;;
		*Exit) i3-msg exit ;;
        	*Suspend) systemctl suspend ;;
        	*Hibernate) systemctl hibernate ;;
		*Reboot) systemctl reboot ;;
		*Shutdown) systemctl poweroff
            esac
