#!/bin/bash
#
# By Birkhoff
#

MENU="$(rofi -config "~/.config/polybar/topy/scripts/rofi/rofin.rasi" -sep "|" -dmenu -i -p 'System' -location 3 -xoffset -5 -yoffset 40 -width 10 -hidescrollbar -line-padding 4 -padding 25 -lines 6 <<< "> Lock|> Exit|> Suspend|> Hibernate|> Reboot|> Shutdown")"
            case "$MENU" in
		*Lock) ~/.bin/blurlock ;;
		*Exit) i3-msg exit ;;
        	*Suspend) systemctl suspend ;;
        	*Hibernate) systemctl hibernate ;;
		*Reboot) systemctl reboot ;;
		*Shutdown) systemctl poweroff
            esac
