--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#2E3440"
foreground="#D8DEE9"
cursor="#D8DEE9"

-- Colors
color0="#3B4252"
color1="#BF616A"
color2="#A3BE8C"
color3="#EBCB8B"
color4="#81A1C1"
color5="#B48EAD"
color6="#88C0D0"
color7="#E5E9F0"
color8="#4C566A"
color9="#BF616A"
color10="#A3BE8C"
color11="#EBCB8B"
color12="#81A1C1"
color13="#B48EAD"
color14="#B48EAD"
color15="#ECEFF4"
