foreground   #cbdee3
background   #1b1e25
cursor       #cbdee3

color0       #1b1e25
color8       #8e9b9e
color1       #5C758D
color9       #5C758D
color2       #6D92A9
color10      #6D92A9
color3       #78B4C8
color11      #78B4C8
color4       #9BADA1
color12      #9BADA1
color5       #87ADC6
color13      #87ADC6
color6       #8BC1D1
color14      #8BC1D1
color7       #cbdee3
color15      #cbdee3
