# Shell variables
# Generated by 'wal'
wallpaper='/home/birkhoff/Images/wallhaven/wallhaven-x16kdd.jpg'

# Special
background='#111f25'
foreground='#c8d5e3'
cursor='#c8d5e3'

# Colors
color0='#111f25'
color1='#124AB2'
color2='#104FBD'
color3='#396BA7'
color4='#4573B1'
color5='#4187D7'
color6='#5391D9'
color7='#c8d5e3'
color8='#8c959e'
color9='#124AB2'
color10='#104FBD'
color11='#396BA7'
color12='#4573B1'
color13='#4187D7'
color14='#5391D9'
color15='#c8d5e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
