foreground   #c4bbcc
background   #101115
cursor       #c4bbcc

color0       #101115
color8       #89828e
color1       #83687E
color9       #83687E
color2       #5B7294
color10      #5B7294
color3       #8C7795
color11      #8C7795
color4       #658CAA
color12      #658CAA
color5       #688BB1
color13      #688BB1
color6       #79A9C4
color14      #79A9C4
color7       #c4bbcc
color15      #c4bbcc
