--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/birkhoff/Images/wallpaper/dnord4k_dark.png"

-- Special
background="#101115"
foreground="#c4bbcc"
cursor="#c4bbcc"

-- Colors
color0="#101115"
color1="#83687E"
color2="#5B7294"
color3="#8C7795"
color4="#658CAA"
color5="#688BB1"
color6="#79A9C4"
color7="#c4bbcc"
color8="#89828e"
color9="#83687E"
color10="#5B7294"
color11="#8C7795"
color12="#658CAA"
color13="#688BB1"
color14="#79A9C4"
color15="#c4bbcc"
