# Shell variables
# Generated by 'wal'
wallpaper='/home/birkhoff/Images/wallpaper/dnord4k_dark.png'

# Special
background='#101115'
foreground='#c4bbcc'
cursor='#c4bbcc'

# Colors
color0='#101115'
color1='#83687E'
color2='#5B7294'
color3='#8C7795'
color4='#658CAA'
color5='#688BB1'
color6='#79A9C4'
color7='#c4bbcc'
color8='#89828e'
color9='#83687E'
color10='#5B7294'
color11='#8C7795'
color12='#658CAA'
color13='#688BB1'
color14='#79A9C4'
color15='#c4bbcc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
