--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/birkhoff/Images/Nord/underwater.png"

-- Special
background="#1b1e25"
foreground="#cbdee3"
cursor="#cbdee3"

-- Colors
color0="#1b1e25"
color1="#5C758D"
color2="#6D92A9"
color3="#78B4C8"
color4="#9BADA1"
color5="#87ADC6"
color6="#8BC1D1"
color7="#cbdee3"
color8="#8e9b9e"
color9="#5C758D"
color10="#6D92A9"
color11="#78B4C8"
color12="#9BADA1"
color13="#87ADC6"
color14="#8BC1D1"
color15="#cbdee3"
