;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Modified░By░Birkhoff░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; Active Colors
background = ${xrdb:color0:#222}
background-alt = #C4C7C5
foreground = ${xrdb:color7:#222}
foreground-alt = #C4C7C5
primary = ${xrdb:color2:#222}

trans = #00000000
white = #FFFFFF
black = #000000

;; Material Colors
;red = #EC7875
;pink = #EC6798
;purple = #BE78D1
;blue = #75A4CD
;cyan = #00C7DF
;teal = #00B19F
;green = #61C766
;lime = #B9C244
;yellow = #EBD369
;amber = #EDB83F
;orange = #E57C46
;brown = #AC8476
;gray = #9E9E9E
;indigo = #6C77BB
;blue-gray = #6D8895

red = ${xrdb:color2:#222}
pink = ${xrdb:color2:#222}
purple = ${xrdb:color2:#222}
blue = ${xrdb:color2:#222}
cyan = ${xrdb:color2:#222}
teal = ${xrdb:color2:#222}
green = ${xrdb:color2:#222}
lime = ${xrdb:color2:#222}
yellow = ${xrdb:color2:#222}
amber = ${xrdb:color2:#222}
orange = ${xrdb:color2:#222}
brown = ${xrdb:color2:#222}
gray = ${xrdb:color2:#222}
indigo = ${xrdb:color2:#222}
blue-gray = ${xrdb:color2:#222}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
